[package]
name = "bgselector-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = { version = "1.17.1", default-features = false, features = ["compat-1-2", "backend-winit-wayland", "renderer-femtovg"] }
image = { version = "0.24", default-features = false, features = ["jpeg", "png", "webp"] }
dirs = "5.0"
walkdir = "2.5.0"
rand = "0.10.2"

[build-dependencies]
slint-build = "1.17.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = "z"     
lto = true        
codegen-units = 1  
strip = true     
panic = "abort" 
